apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: treasury-market-

commonLabels:
  bot: treasury-market

patchesStrategicMerge:
  - deployment_set_bot.yaml
