apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: next-rebase-

commonLabels:
  bot: next-rebase

patchesStrategicMerge:
  - deployment_set_bot.yaml
