apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: treasury-carbon-

commonLabels:
  bot: treasury-carbon

patchesStrategicMerge:
  - deployment_set_bot.yaml
