apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: manic-price-

commonLabels:
  bot: manic-price

patchesStrategicMerge:
  - deployment_set_bot.yaml
