apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: staking-rewards-

commonLabels:
  bot: staking-rewards

patchesStrategicMerge:
  - deployment_set_bot.yaml
