apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: klima-price-

commonLabels:
  bot: klima-price

patchesStrategicMerge:
  - deployment_set_bot.yaml
