apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namePrefix: bond-alerts-

commonLabels:
  bot: bond-alerts

patchesStrategicMerge:
  - deployment_set_bot.yaml
