name: Continuous Integration

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          # ignore: "F401"
          # exclude: "src/ignoreme.py"
          max-line-length: "120"
          path: "src"
  validate-k8s:
    runs-on: ubuntu-latest
    name: Validate k8s manifests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2.1.0-rc
        with:
          kustomize-version: "4.5.4"
      - name: Update secret properties with injected secrets
        run: touch $GITHUB_WORKSPACE/k8s/secret.properties
      - name: Kustomize
        run: kustomize build k8s > /tmp/kustomized.yaml
      - uses: azure/k8s-lint@v2.0
        with:
          manifests: |
            /tmp/kustomized.yaml
